name: GitHub Profile 3D Contrib

on:
  schedule: # Executa a cada 24 horas
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permite executar manually

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    
    # --- AQUI ESTÁ A CORREÇÃO ---
    permissions:
      contents: write
    # -------------------------

    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "chore: update 3d contrib graph"
          git push
